sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t8BkoYeiEdWZXqqtH8h
    access-key-secret: hFg9tT7yJvaGHaYflB3DQpsIoltA7W
    bucket-name: web-tlias-yht
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxa9042d28e0eacaa7
    secret: 34052f1f5935ea633c19e53adbb368b8